version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdbrepo
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
#    volumes:
#      - local_pgdata:/var/lib/postgresql/data
#      - ./db/data.sql:/docker-entrypoint-initdb.d/create_tables.sql